name: Documentation

on:
  schedule:
    # Run once every week on Sunday
    - cron: 0 0 * * 0
  push:
    paths:
      # Or if an include has been updated
      - 'includes/*.toml'
      # Manual trigger
      - 'trigger.txt'

jobs:
  documentation:
    name: Build Documentations

    runs-on: ubuntu-latest

    steps:
      - name: Checkout manifests
        uses: actions/checkout@v2

      - name: Download Chumbucket
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: "rumblefrog/sp-docgen"
          version: "tags/cb-0.1.0"
          file: "chumbucket"

      - name: Chumbucket +x
        run: sudo chmod +x chumbucket

      - name: Process manifests
        run: |
          for i in includes/*.toml; do
            [ -f "$i" ] || break
            ./chumbucket $i -o $i.out
          done
